In [1]:
import pandas as pd
from pathlib import Path


# Ler arquivos
df = pd.read_csv('/home/felipe/Projeto/Portfolio/Portfolio2/multi_brand_marketing/data/processed/unified_campaign_data.csv')
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025,Nykaa
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025,Nykaa
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025,Nykaa
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025,Nykaa
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024,Nykaa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,TI-CMP-56550,Influencer,Tier 2 City Customers,11,"Instagram, YouTube, Email",60137,3799,1539,1099,454986,213.21,0.94,Bengali,10.70,Youth,12-11-2024,Tira
166661,TI-CMP-56551,SEO,Working Women,20,"Google, Instagram",54886,1578,634,343,136514,436.24,-0.09,English,4.66,Working Women,25-08-2024,Tira
166662,TI-CMP-56552,Email,Tier 2 City Customers,13,"Facebook, Instagram",97954,11480,4567,2144,445952,78.77,1.64,Bengali,18.57,Premium Shoppers,15-04-2025,Tira
166663,TI-CMP-56553,Influencer,Premium Shoppers,22,"Google, Email",11669,458,122,44,26884,2578.39,-0.76,English,5.35,Working Women,21-07-2024,Tira
166664,TI-CMP-56554,Paid Ads,Working Women,9,Instagram,50497,1604,542,363,281688,151.44,4.12,English,4.97,Premium Shoppers,02-05-2025,Tira

In [2]:
df.columns

Index(['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration',
       'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions',
       'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score',
       'Customer_Segment', 'Date', 'Brand'],
      dtype='object')

In [3]:
import numpy as np

df["CTR"] = np.where(df["Impressions"] > 0, df["Clicks"] / df["Impressions"], 0) 

df["conversion_rate"] = np.where(df["Clicks"] > 0, df["Conversions"] / df["Clicks"], 0) 

df["CPC"] = np.where(df["Clicks"] > 0, df["Acquisition_Cost"] / df["Clicks"], 0)

df["CPA"] = np.where(df["Conversions"] > 0, df["Acquisition_Cost"] / df["Conversions"], 0)

In [4]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,...,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand,CTR,conversion_rate,CPC,CPA
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,...,6.14,Hindi,20.98,College Students,29-04-2025,Nykaa,0.106498,0.382554,0.018036,0.047146
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,...,3.26,Hindi,7.24,College Students,06-04-2025,Nykaa,0.036176,0.408612,0.054450,0.133257
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,...,1.88,English,25.03,College Students,14-01-2025,Nykaa,0.140448,0.346013,0.041522,0.120000
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,...,0.60,Hindi,13.15,College Students,04-06-2025,Nykaa,0.095479,0.112564,0.029605,0.263010
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,...,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024,Nykaa,0.038639,0.336094,0.061074,0.181717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,TI-CMP-56550,Influencer,Tier 2 City Customers,11,"Instagram, YouTube, Email",60137,3799,1539,1099,454986,...,0.94,Bengali,10.70,Youth,12-11-2024,Tira,0.063172,0.289287,0.056123,0.194004
166661,TI-CMP-56551,SEO,Working Women,20,"Google, Instagram",54886,1578,634,343,136514,...,-0.09,English,4.66,Working Women,25-08-2024,Tira,0.028751,0.217364,0.276451,1.271837
166662,TI-CMP-56552,Email,Tier 2 City Customers,13,"Facebook, Instagram",97954,11480,4567,2144,445952,...,1.64,Bengali,18.57,Premium Shoppers,15-04-2025,Tira,0.117198,0.186760,0.006861,0.036740
166663,TI-CMP-56553,Influencer,Premium Shoppers,22,"Google, Email",11669,458,122,44,26884,...,-0.76,English,5.35,Working Women,21-07-2024,Tira,0.039249,0.096070,5.629672,58.599773
166664,TI-CMP-56554,Paid Ads,Working Women,9,Instagram,50497,1604,542,363,281688,...,4.12,English,4.97,Premium Shoppers,02-05-2025,Tira,0.031764,0.226309,0.094414,0.417190

In [5]:
df["ROAS"] = np.where(df["Acquisition_Cost"] > 0, df["Revenue"] / df["Acquisition_Cost"], 0)

df["Revenue_per_click"] = np.where(df["Clicks"] > 0, df["Revenue"] / df["Clicks"], 0)

df["Revenue_per_conversion"] = np.where(df["Conversions"] > 0, df["Revenue"] / df["Conversions"], 0)

In [21]:
import os

output_path = os.path.join(processed_dir, 'df_complete.csv')
df.to_csv(output_path, index=False)

In [6]:
df["conversion_rate"].mean()

np.float64(0.21945369723635363)

In [7]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,...,Customer_Segment,Date,Brand,CTR,conversion_rate,CPC,CPA,ROAS,Revenue_per_click,Revenue_per_conversion
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,...,College Students,29-04-2025,Nykaa,0.106498,0.382554,0.018036,0.047146,16819.913537,303.365010,793.0
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,...,College Students,06-04-2025,Nykaa,0.036176,0.408612,0.054450,0.133257,5785.804347,315.039747,771.0
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,...,College Students,14-01-2025,Nykaa,0.140448,0.346013,0.041522,0.120000,2175.000000,90.309349,261.0
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,...,College Students,04-06-2025,Nykaa,0.095479,0.112564,0.029605,0.263010,1513.253302,44.800428,398.0
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,...,Tier 2 City Customers,29-12-2024,Nykaa,0.038639,0.336094,0.061074,0.181717,2267.261592,138.470745,412.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,TI-CMP-56550,Influencer,Tier 2 City Customers,11,"Instagram, YouTube, Email",60137,3799,1539,1099,454986,...,Youth,12-11-2024,Tira,0.063172,0.289287,0.056123,0.194004,2133.980583,119.764675,414.0
166661,TI-CMP-56551,SEO,Working Women,20,"Google, Instagram",54886,1578,634,343,136514,...,Working Women,25-08-2024,Tira,0.028751,0.217364,0.276451,1.271837,312.933248,86.510773,398.0
166662,TI-CMP-56552,Email,Tier 2 City Customers,13,"Facebook, Instagram",97954,11480,4567,2144,445952,...,Premium Shoppers,15-04-2025,Tira,0.117198,0.186760,0.006861,0.036740,5661.444712,38.845993,208.0
166663,TI-CMP-56553,Influencer,Premium Shoppers,22,"Google, Email",11669,458,122,44,26884,...,Working Women,21-07-2024,Tira,0.039249,0.096070,5.629672,58.599773,10.426662,58.698690,611.0
166664,TI-CMP-56554,Paid Ads,Working Women,9,Instagram,50497,1604,542,363,281688,...,Premium Shoppers,02-05-2025,Tira,0.031764,0.226309,0.094414,0.417190,1860.063391,175.615960,776.0

In [8]:
df['Acquisition_Cost'].sum()

np.float64(62681853.33)